# Global variables
cluster_name: greyjoy
cluster_env: PROD
cluster_prefix: datsci-exo
cluster_init_nb_nodes: 3
cluster_ssh_key: datsci-exo-kp
cluster_security_group_name: datsci-exo-sg-greyjoy
# Cluster access
cluster_ssh_group_names: [datsci-exo-sg-castleblack,default]
cluster_service_group_names: [default]
