
  # Makes easier to reference the masters
  - set_fact:
      cluster_master_1_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
      cluster_master_2_ip: "{{ hostvars[groups['masters'][1]]['ansible_host'] }}"
      cluster_master_3_ip: "{{ hostvars[groups['masters'][2]]['ansible_host'] }}"

  # Create and register the workers
  - name: Start cluster workers
    local_action:
      module: cs_instance
      name: "{{ cluster_prefix }}-{{ cluster_name }}-worker-{{ item }}"
      zone: "{{ exo_zone }}"
      template: "{{ exo_template }}"
      service_offering: "{{ exo_instance_type }}"
      ssh_key: "{{ cluster_ssh_key }}"
      security_groups: [ '{{ cluster_security_group_name }}-worker' ]
      tags:
        - { key: env, value: "{{ cluster_env }}" }
        - { key: cluster_name, value: "{{ cluster_name }}" }
        - { key: cluster_role, value: worker }
      user_data: "{{ lookup('template', '../templates/worker-cloud-config.j2') }}"
    with_sequence: count={{ nb_nodes }}
    register: worker_nodes
    tags: vm

  - add_host:
      groups: workers
      hostname: "{{ item.display_name }}"
      ansible_host: "{{ item.default_ip }}"
      ansible_user: core
      ansible_python_interpreter: /opt/bin/python
    with_items: "{{ worker_nodes.results }}"
    tags: vm
