# Infrastructure certificates

- file:
    path: /etc/ssl/infra-etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755
  tags: crt

- copy:
    src: ./secret/ssl/infra/etcd-ca.pem
    dest: /etc/ssl/infra-etcd/ca.pem
  tags: crt

- copy:
    src: ./secret/ssl/infra/{{ ansible_hostname }}/etcd.pem
    dest: /etc/ssl/infra-etcd/etcd.pem
  tags: crt

- copy:
    src: ./secret/ssl/infra/{{ ansible_hostname }}/etcd-key.pem
    dest: /etc/ssl/infra-etcd/etcd-key.pem
    owner: etcd
    group: etcd
    mode: 0600
  tags: crt

- copy:
    src: ./secret/ssl/infra/{{ ansible_hostname }}/etcd-client.pem
    dest: /etc/ssl/infra-etcd/etcd-client.pem
  tags: crt

- copy:
    src: ./secret/ssl/infra/{{ ansible_hostname }}/etcd-client-key.pem
    dest: /etc/ssl/infra-etcd/etcd-client-key.pem
    owner: etcd
    group: etcd
    mode: 0600
  tags: crt

# kubernetes etcd certificates

- file:
    path: /etc/ssl/kubernetes-etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/etcd-ca.pem
    dest: /etc/ssl/kubernetes-etcd/ca.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd.pem
    dest: /etc/ssl/kubernetes-etcd/etcd.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd-key.pem
    dest: /etc/ssl/kubernetes-etcd/etcd-key.pem
    owner: etcd
    group: etcd
    mode: 0600
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd-client.pem
    dest: /etc/ssl/kubernetes-etcd/etcd-client.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd-client-key.pem
    dest: /etc/ssl/kubernetes-etcd/etcd-client-key.pem
    owner: etcd
    group: etcd
    mode: 0600
  tags: crt

# kubernetes certificates

- file:
    path: /etc/kubernetes/ssl
    state: directory
    mode: 0755
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/apiserver-ca.pem
    dest: /etc/kubernetes/ssl/apiserver-ca.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/etcd-ca.pem
    dest: /etc/kubernetes/ssl/etcd-ca.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/apiserver.pem
    dest: /etc/kubernetes/ssl/apiserver.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/apiserver-key.pem
    dest: /etc/kubernetes/ssl/apiserver-key.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/service-account.pem
    dest: /etc/kubernetes/ssl/service-account.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/service-account-key.pem
    dest: /etc/kubernetes/ssl/service-account-key.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/apiserver-client.pem
    dest: /etc/kubernetes/ssl/apiserver-client.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/apiserver-client-key.pem
    dest: /etc/kubernetes/ssl/apiserver-client-key.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd-client.pem
    dest: /etc/kubernetes/ssl/etcd-client.pem
  tags: crt

- copy:
    src: ./secret/ssl/kubernetes/{{ ansible_hostname }}/etcd-client-key.pem
    dest: /etc/kubernetes/ssl/etcd-client-key.pem
  tags: crt
